### ISSUE TITLE
Rewrite the dictation into properly written sentences.

### ISSUE THREAD

**Issue by cryptoniooo** [DevEmperor/Dictate#2]
This is a great tool but it comes with a problem. You can dictate but if you use this with many other people there should be an option to plug it to OpenAI and have OpenAI revise the text and either put it as conversational, sarcastic, funny, summarize it, shorten it because it's not the same speaking as when we write and with that the tool can be used for day-to-day texting as other people would see and it would not make sense to text them exactly like we speak. I think this could make the tool the ultimate dictation tool in the market if this is fixed.

So basically we just need an option to turn on or turn off if we want to use this filter. It could be the text to write filter and then we turn it on and we decide what filter do we want. Do we want it to be summarized, make it more clear, rewrite, many other options that we can tell OpenAI what to do with what we just dictated and then immediately just paste it after we dictate without me having to right now dictate and then paste it to chatGBD and then paste it back to the chat with people as it does not make sense to dictate and just paste it. Like for example this whole text I've dictated it and certain parts do not make sense but the problem is you don't always have the time to go to chatGBD and edit so I think making it frictionless it could be really a revolutionary tool.

**Comment by DevEmperor** [comment]
Thank you very much for your feedback and this great idea. In fact, it has been on my to-do list for some time now to be able to edit the recognised text with various prompts after recording. That would be pretty much in line with your idea.
My idea was that you could define different prompts yourself in the settings, where you could then translate, summarise or rephrase in a different style directly after recording, for example. Then you could also define a prompt that instructs ChatGPT to put the spoken text into a meaningful grammatical context. I will definitely be adding this feature in the near future. Stay tuned. :)

**Comment by cryptoniooo** [comment]
Hey, I was wondering, is there any way we could speed up this feature? Maybe we can align incetives here? This is actually super useful...

Sent from Proton Mail Android

-------- Original Message --------

**Comment by DevEmperor** [comment]
Hey, I also noticed how extremely amazing this feature would be, and trust me, I am currently putting all of my free time into this project, and specifically into this feature. The next update will be massive. I will keep you updated. :)

**Comment by cryptoniooo** [comment]
I just saw you sent an update and I was wondering what are the instructions for the prompt like I told it to make it sound professional but I don't I don't think he's working I'm using just the open AI APY do I need something else

Sent from Proton Mail Android

-------- Original Message --------

**Comment by DevEmperor** [comment]
Hey, sorry for the misunderstanding at this point. The update to version 1.5 does not yet include the rewording feature you suggested. The style promp in the settings allows you to guide the model in a certain direction. For example, you can enter a random text where everything is lowercase and without punctuation, and Whisper will no longer add punctuation or capital letters in all future recordings. [Here you can read more about this feature.](https://platform.openai.com/docs/guides/speech-to-text/prompting)

As mentioned, I am working very hard on the feature you suggested, which will be much bigger than what was included in the update to version 1.5. I am about 40% through the work, but I am making very good progress. Until then, I can only ask for your patience. I will notify you in this thread as soon as I am finished, even before the update is released on Google Play. :)

**Comment by cryptoniooo** [comment]
Okay, sounds good. I got confused for a second. No worries. Also, if you want to put on the roadmap or might be interesting for you to think about it now, and I don't even know if this is possible, but this is pushing it to the limit in the sense of making it really cool. You know how there is custom GPTs that we upload our information. So for example, I upload all my text messages from the past four years into a custom GPT PDF, train the model on it and then imagine what it's like if I could plug it in here. And then I can just, I speak and then OpenAI just spits out the text as I've read in the past years. And then I can do the same with any books, authors, or any really type of content. And then it styles it on that way that could open so many unlimited possibilities. I could even just speak and it would recite poems. I think it could be really cool, but I feel like that's pushing it because I don't know how well be the integrations for a custom GPT and that's more complex. And I think it's already pretty cool Already working on it.. So yeah, that was just an idea. I hope you're having a good day.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by DevEmperor** [comment]
Hey again,
as you can see in [these](https://github.com/DevEmperor/Dictate/commit/3f7aec7ef5af69c6fc801b4feee99bf3b5de5399) [three](https://github.com/DevEmperor/Dictate/commit/383d178e6cba1692832717a3f3d1aec0344914ef) [commits](https://github.com/DevEmperor/Dictate/commit/a477403bec34d54a8c717628a10988e8dc6ade31), I have finally added this amazing feature. I've tested it a bit with some prompts (also the one you suggested) and this is really changing a lot. The possibilities are endless, and I want to thank you for this great idea. :)

I will release the update now, and within two to three days, you will be able to enjoy this too.

**Comment by DevEmperor** [comment]
Sadly, your idea with the custom GPTs is not possible, because the OpenAI API does not offer any interface for interacting with these GPT models. We can only use the public GPT-4 or GPT-3.5 Models. :)

**Comment by cryptoniooo** [comment]
Can you send me the apk directly my email so I can try it?

-------- Original Message --------

**Comment by cryptoniooo** [comment]
***@***.***

**Comment by DevEmperor** [comment]
Your email address has been obscured by GitHub for security reasons. I am simply sending you a one-time link to download.
https://workupload.com/file/aSz36nmA2c3

**Comment by cryptoniooo** [comment]
Cool, I got it to work, but is it possible to not have to click the button to make it work and just automatically output and go through the prompt?

-------- Original Message --------

**Comment by cryptoniooo** [comment]
Hey,

How are you doing? I've noticed some errors. For example, sometimes the audio continues playing, and the minutes keep counting even after I attempt to stop it. I wonder what the solution is. Not long ago, I had the same issue when putting my Z-fold horizontally; it would lose entire audios.

I'm reaching out to ask, do we have any way to add a custom GPT into the process when handling the audio? My problem is that I write very long texts, or I use the speech-to-text feature for extensive texts, not storytelling, and it always maintains the same tone and voice. I want something more customized based on my edited past texts that would reflect my voice. This would allow me to select the entire text and then use the custom GPT, maybe an API, to output the entire speech-to-text notes I wrote or dictated out loud, maintaining the same text quality.

I think this could be really interesting and useful for writers. For example, if I'm trying to write a book, conveying all these thoughts or stories out loud would be easier. Then, using the app, with the click of a button after speech-to-text conversion, it could apply my voice and the tone and style of previous books I've used, rather than forcing me to sit for hours structuring text and writing. If I train a custom GPT on hundreds of pages I've written before, it could output in the same style; it just needs the information.

I believe this could be really cool and marketable to writers lacking time to write. For example, when we go on a hike, or when we're out walking, which is when I do most of my work, they could just speech-to-text their inspiration and capture it immediately.

I must say, your app has been really impactful, particularly in my work life, as many clients demand a lot from me. Usually, I wouldn't be able to type so much information, but this way, I can manage it. They feel heard and that I’m present and helpful, so it really benefits me in that regard. I've even tried Apple dictation and Google Voice, but none compare to it. I think, at the end of the day, because this uses ChatGPT's API, the ultimate level would be to have, say, 10 minutes' worth of audio, send it to the ChatGPT API, and let it use my custom GPT to polish everything, using my own tone of voice and words. Then, I could have a blog written or post about XYZ.

Anyways, this was just my idea. Hope you're doing well, and thank you for your work.

-------- Original Message --------

**Comment by DevEmperor** [comment]
Hey,
thanks for your ideas and bug reports. :)

First of all, the bug that everything recorded is lost, after flipping your phone, is already known to me. The problem is, that Android resets the whole created views, which is why the keyboard behaves very strange then. The recording continues in the background thread, but the UI is lost. Currently, I am not working on a fix for this, because there isn't that much time for me to work on this project. I suggest, that you simply do not flip your phone while recording. :)

About your idea with custom GPTs: Somebody else already asked me a similar question, but the problem is, that as a developer, I have no access to custom GPT models. The API simply doesn't offer this and I can only access the official models (GPT-4 Turbo, GPT 3.5, etc.) So sadly, I can not integrate this idea. Of course, you could add a lot of your personal texts to a custom prompt, which is sent every time you record something. Even if that would use much more tokens, you could try this approach and send me feedback.

I am really happy, that this app helps you so much. Thanks for your ideas and your feedback. :)

**Comment by cryptoniooo** [comment]
Okay, thank you for your message. So, if I want to do the custom prompt with, let's say, a thousand word text that I created, so it uses that tone of voice and similar styling, how do you suggest that I code the custom prompt? Is there a specific thing to say? Is there a specific set of commands? Or just simply say, I use this tone of voice and conversational tone, etc. Any suggestions to make it work really accurately and work really well?

-------- Original Message --------

**Comment by DevEmperor** [comment]
Yes, I suggest that you say at first something like "I always write things with a specific tone. I am going to send you a long text that I wrote, and you should take the tone of my text and rewrite / reword the second text so that it sounds like the tone that I used in the long first text." Then you add your long text and if you reword a transcribed text, it will automatically add your highlighted recorded text and send it to GPT.
I hope this helps. :)

**Comment by cryptoniooo** [comment]
I tried to do it, but apparently it cannot handle very large inputs, and when it comes to the output, it just rewrites super short texts. What I did was create a custom GPT, and then I used text-to-speech there. Interestingly, your app can handle over 7 minutes of text-to-speech; it didn't crash and pasted the text. In the past, it crashed a couple of times, and I'm not sure if it was because of the API, but when I tried OpenAI's text-to-speech, it would crash. It's so frustrating when you're speaking for 10 minutes narrating a story and you have to do it all over again. It makes me think that there should be a record feature in the settings of your app, which we can toggle on and off. For some important audios, I could just record so I wouldn't lose them, because if they’re over 7, 10, or 20 minutes, we might lose everything when it hasn’t been processed. I was wondering if this is a feature you could add, since I'm going to be using it so many times, narrating for probably over 30 minutes, to the text-to-speech, and then pasting it into OpenAI. OpenAI would then turn it into a whole story, I mean on ChatGPT, CustomGPT. Let me know if this feature is possible; I'd be happy to make another donation for it. It's actually the only piece of the puzzle because if I keep writing or speaking for so long and then lose everything, it’s just terrible for the flow and I have to redo the stories. It can be very frustrating.

-------- Original Message --------

**Comment by DevEmperor** [comment]
Hey, I am not sure if I understood you correctly. But there is already a settings option to activate a "resend button". If you toggle this on, there will always be a "resend"-button next to the recording button. If you 10 minutes recording interrupts (no matter what caused the interruption of loss of the recording), you can simply click on the resend button and the last recorded part will be sent again to OpenAI for transcription.
I hope this helps you with your problem. If not, let me know. :)
