### ISSUE TITLE
No feedback email

### ISSUE THREAD

**Issue by cryptoniooo** [DevEmperor/Dictate#3]
If a user wants to leave feedback, when clicking on the option to leave feedback and opening an email, there is no automatically added email to send our feedback.

**Comment by DevEmperor** [comment]
Okay, that's strange, because on my two test devices (from different manufacturers) a query opens where I can select my e-mail app, and then a draft is created that is addressed to my contact address. What is it doing for you? :)

**Comment by cryptoniooo** [comment]
Yeah, it doesn't work with a proton mail

**Comment by DevEmperor** [comment]
Does Proton Mail at least open as an app for you? Or does nothing happen at all?

**Comment by cryptoniooo** [comment]
It opens

Sent from Proton Mail Android

-------- Original Message --------

**Comment by DevEmperor** [comment]
The problem lies with ProtonMail. The app doesn't seem to support mailto-links, so you have to enter my contact address manually in an email. An update will be released in a few days where my email address will be below the give feedback button. :)
