### ISSUE TITLE
groq support

### ISSUE THREAD

**Issue by vortex1024** [DevEmperor/Dictate#6]
hello,
groq.com also has a whisper api, and it also has a generous free tier. could you add support for it in your keyboard?
the effort should not be too bbig. I see you already support custom whisper host, the thing is groq's url contains "/openapi" before the normal openai api path (https://api.groq.com/openai/v1/audio/transcriptions), and entering that in the host field in settings crashes the app, probably since it does not expect an address in there, but just a host.
Thanks.

**Comment by DevEmperor** [comment]
I'd like to investigate this issue further, but I cannot sign in to groq.com. Could you send me an API key for testing to my email-address, so that I can fix this issue? :)
contact@devemperor.net

**Comment by vortex1024** [comment]
I sent it. Did you receive it?

**Comment by DevEmperor** [comment]
Yes, thank you very much, I received it. However, I have been too busy the last few days adding other features that I haven't had the chance to look into it further yet. I will definitely take a look at it. :)

**Comment by DevEmperor** [comment]
I have now had a closer look at groq's API and apparently they are using a different scheme than OpenAI. So unfortunately I can't support groq because the library is only orientated towards OpenAI.
